import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@radix-ui/react-separator";
import { AppSidebar } from "../components/sidebar/app-sidebar";
import { Bell, BellDot, ChevronDown } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <SidebarProvider>
          <Toaster richColors position="top-right" closeButton />
          <AppSidebar />
          <SidebarInset className="bg-[#EAEAEA]">
            <header className="m-2 px-4 py-3 bg-white rounded-[10px] flex items-center justify-between shadow">
              <div className="flex items-center gap-4">
                <SidebarTrigger className="-ml-1" />
                <div className="flex flex-col">
                  <h1 className="text-2xl font-semibold text-[#369FFF]">Hello IIC 4.0, welcome back!</h1>
                  <p className="text-sm text-gray-500">Operator &gt; Operator Status</p>
                </div>
              </div>

              <div className="flex items-center gap-6">
                <div className="relative">
                  <Bell className="w-6 h-6 text-gray-700" />
                  <span className="absolute top-0 right-0 h-2.5 w-2.5 bg-red-500 rounded-full" />
                </div>

                <div className="flex items-center gap-3 px-3 py-2 bg-[#DDEEFF] rounded-md">
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                    <AvatarFallback>I4</AvatarFallback>
                  </Avatar>
                  <div className="flex flex-col justify-center text-lg">
                    <span className="text-black font-medium">Industry 4.0</span>
                    <span className="text-blue-600">IIC 4.0</span>
                  </div>
                  <ChevronDown className="ml-2 text-gray-600" />
                </div>
              </div>
            </header>

            {children}
            {/* <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
              <div className="grid auto-rows-min gap-4 md:grid-cols-3">
                <div className="bg-muted/50 aspect-video rounded-xl" />
                <div className="bg-muted/50 aspect-video rounded-xl" />
                <div className="bg-muted/50 aspect-video rounded-xl" />
                <p>ahihi</p>
              </div>
              <div className="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min" />
            </div> */}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
